# docker-compose.yml - Docker Compose configuration for the application

version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app  # Mount the current directory to /app in the container
    ports:
      - "5000:5000"  # Map port 5000 on the host to port 5000 in the container
    environment:
      DATABASE_URL: "sqlite:///mydatabase.db"  # Adjust as necessary
      # Add other environment variables as needed
    depends_on:
      - db

  db:
    image: postgres:latest  # Use the latest PostgreSQL image
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    volumes:
      - db_data:/var/lib/postgresql/data  # Persist database data

volumes:
  db_data:  # Named volume for PostgreSQL data
